name: "Marginalia"
description: "a life stream"

url: 'https://davidegallesi.com' 
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

twitter_username: davidegallesi

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-feed
  
  
paginate: 7
paginate_path: /page-:num

#disqus-id: your-disqus-id


sass:
    style: :compressed
    sass_dir: assets/css/
    

