site: Marginalia
url: https://www.davidegallesi.com
title: Marginalia
description: A digital garden
twitter:
  username: davidegallesi
  card: summary
  creator: davidegallesi
  image: favicon.png
author:
  twitter: davidegallesi
  name: Davide Gallesi
  avatar: favicon.png
  email: #youremail
  url: ""
permalink: pretty

baseurl: ""



markdown: kramdown
highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-wikilinks  

collections:
  pages:
    output: true
  #  permalink: /:name
  posts:
    output: true
    #permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
