site: Marginalia
url: https://davidegallesi.github.io
title: Marginalia
description: A digital garden
twitter:
  username: davidegallesi
  card: summary
  creator: davidegallesi
  image: favicon.png
author:
  twitter: davidegallesi
  name: Davide Gallesi
  avatar: favicon.png
  email: #youremail
  url: ""
permalink: pretty

baseurl: ""



markdown: kramdown
highlighter: rouge

exclude:
  - .jekyll-cache
  - sync.sh
  - publish.sh
  - netlify.toml
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-wikilinks  

wikilinks:
  attributes:
    enabled: true
  css:
    exclude: []
    name:
      typed: 'typed'
      wiki: 'wiki-link'
      web: 'web-link'
      invalid_wiki: 'invalid-wiki-link'
      embed_container: 'embed-container'
      embed_title: 'embed-title'
      embed_content: 'embed-content'
      embed_link: 'embed-wiki-link'
      embed_image_container: 'embed-image-container'
      embed_image: 'embed-image'
  enabled: true
  exclude: []


collections:
  pages:
    output: true
  #  permalink: /:name
  posts:
    output: true
    #permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      