  # Site settings
title:          marginalia
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/"
url:            "https://davidegallesi.github.io"


# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
paginate_path: ./page:num/


# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Davide Gallesi
  url:          https://davidegallesi.com
  email:        

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
 
  # - jemoji #Uncomment this to allow emoji in your post



# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
 
remote_theme: chesterhow/tale
