# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
# - index.md
    # - pages/index.md
    # - pages/about.md
    - pages/archive.html
    - pages/tsundoku.md
    - pages/now.md
#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'


style: dark # light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

url: "https://www.davidegallesi.com"

plugins:
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown
highlighter: rouge
